### ISSUE TITLE
Sub-cards?

### ISSUE THREAD

**Issue by Grunthos** [nextcloud/deck#2103]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

Sometimes is is nice to have a taks broken into sub-tasks, each with dues dates and notes etc.

**Describe the solution you'd like**

The ability to link cards hierarchically, eg.

Migrate to new ISP:
- Move DNS
- Move mail
- Move Web Server
- Decommission old server

One might argue that this is a 'project', but one might need a third level of hierarchy:
Move Mail
 - Select shortlisy of new storage backend candidates
 - test backed performance
 - select final candidate
 - configure and test migration script for new backend

etc

**Describe alternatives you've considered**

It seems that one needs a structure like:
Board
   List
      Card
         List...

**Comment by stefan-niedermann** [comment]
Have you tried the task syntax
```
- [ ] Item 1
- [x] Item 2
```

which will result in

- [ ] Item 1
- [x] Item 2

and resulting being visible at the card like this:

![grafik](https://user-images.githubusercontent.com/4741199/86518134-27e0b680-be2f-11ea-83e2-ee9daf26bd6f.png)

**Comment by stefan-niedermann** [comment]
Searching the issues resulted in a duplicate of https://github.com/nextcloud/deck/issues/1818

This issue was marked as a duplicate of https://github.com/nextcloud/deck/issues/272 which has been closed with the following comment of the maintainer:

> As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

> If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by Grunthos** [comment]
Damn! I did a search for sub and sub-card etc. But not 'group'!

At least I'm not alone in my interest in this feature.

**Comment by stefan-niedermann** [comment]
No problem :slightly_smiling_face:  @juliushaertl is currently at vacation, let's wait and see how he thinks about it. Personally (as maintainer of the Deck Android app) i can see that this would cause maintenance efforts which are not to underestimate. Therefore we should think hard about implementing (and maintaining) this feature or not.

**Comment by Grunthos** [comment]
Depending on where you see the maintenance issues, it might be sufficient to have an interface that shows:
```
Migrate to New Server
    3 Sub-tasks ((perhaps in a list))
```
Then, clicking on '3 sub-tasks' would just take to you a whole new list (one step down in the hierarchy, with prior tasks hidden); no need to display the whole hierarchy.

One might go so far as to have:

```
Migrate to New Server
    Sub-task 1
    Sub-task 2
    Sub-task 3
```
With an arbitrary long list on the card, then clicking on any of them takes you to the relevant (previously hidden?) BOARD(?)...in that way, you could have 'Triage', 'In Progress' etc for the sub-tasks.

Or it perhaps just hides the higher level of the tree as suggested above, but displays the tasks with the same lists as the main board.

I agree it's complex...and I don't know where your maintenance complexity lies. Any solution that gets a usable hierarchy would be great.

**Comment by putt1ck** [comment]
AFAICT the hierarchy you are asking for exists by use of checklists on a card as described above, or use of lists when a due date is needed for the sub tasks.

**Comment by Grunthos** [comment]
@putt1ck  Not really, unless lists and checklist items canhave names, dates, comments and notes like a card.

I probably should not have presented the dummy UI above -- it was an attempt to sidestep design complexitie, and may have resulted in the wrong impression about what I am asking for (per the first post).

**Comment by putt1ck** [comment]
Lists have subitems that *are* cards. So when we have a complex project we split up the boards; the groupings of the cards are then done with lists.

**Comment by Grunthos** [comment]
Yes...but what I am asking for is cards to have lists UNDER them, I suppose.

I have a fairly traditional (I think) arrangement of lists: #Triage, #Todo, #OnHold, #Inprogress etc

On those lists, I have cards. As per my discussion above, I want to break those cards down into smaller (yet still complex and hence needing it's own card) activities.

Does this make sense? I have this feeling that we are talking at cross-purposes.

**Comment by putt1ck** [comment]
The scenario you describe is where we would break out the card into its own board/list, where list headings would be the "meta card"

**Comment by Grunthos** [comment]
Does that actually work though? Don't  you then need to construct 'In Progress', 'Review', 'Complete' lists for each of these cards?

**Comment by juliushaertl** [comment]
I think having a way to add a different board or stack as a "meta-card" makes sense, similar to how github does it:

![image](https://user-images.githubusercontent.com/3404133/90688547-e7b68580-e26e-11ea-889f-6fd3f9b67655.png)

However it is not on the roadmap currently.

**Comment by muppeth** [comment]
> Have you tried the task syntax
> 
> - [ ] Item 1
> - [x] Item 2

@stefan-niedermann This is already quite cool solution. Would be good to make it into GUI somehow so people not familair with markdown (or not even knowing they can pull this off on deck) will  be able to do it? I think, although not entirely covering the issue at hand would already solve people looking for similar solutions (like me as i got here exactly looking for something like that).

**Comment by hitam4450** [comment]
@stefan-niedermann  Great idea to get started with using markdown much easier....

**Comment by Grunthos** [comment]
I have already addressed why @stefan-niedermann 's solution is not fit for purpose: lack of due dates, lack of ability to add them to other lists etc. ie. they are NOT cards....

**Comment by aproposnix** [comment]
> I have already addressed why @stefan-niedermann 's solution is not fit for purpose: lack of due dates, lack of ability to add them to other lists etc. ie. they are NOT cards....

Hi Grunthos... so if I understand correctly, you want something like this: 

![Selection_127](https://user-images.githubusercontent.com/6204273/93653356-8b1dc600-f9e6-11ea-8f5b-e0a66b270b49.png)

**Comment by Thatoo** [comment]
The list feature is cool but is not working smoothly. When I tick one, it removes all. Plus it would be great if these task woul appear into the tasks app too and can be ticked from it.

**Comment by stefan-niedermann** [comment]
> The list feature is cool but is not working smoothly. When I tick one, it removes all.

@Thatoo please [read here](https://github.com/nextcloud/deck/issues/2595#issuecomment-731172716). I have even pinned the issue, so one does not have ro search the closed ones. This has **nothing** to do with this issue.

> Plus it would be great if these task woul appear into the tasks app too and can be ticked from it.

Has been [discussed here](https://github.com/nextcloud/deck/issues/2254) and is partially resolved. Enhancements will follow in the future. Also: This is *absolutely* not related to the topic of this issue: "Sub-cards".

**Comment by Grunthos** [comment]
Sorry, @aproposnix , didn't see your response until now!

I guess that would be close, but I would then want to do anything with those sub-items that I can do with a card: assign it to a person, put it on another board etc etc. It's hard to tell from your UI image exacttly what can be done with the "tasks". Are they fully-fledged cards?

**Comment by rolandixor** [comment]
The solution of "meta" cards, similar to what Github has, seems like a great approach to this issue, imho.

Separately, it would be useful to have a simple UI (could maybe be implemented with an existing JS, O/S markdown plugin) for adding checkboxes or other formatting.

**Comment by ocervell** [comment]
Any updates here ? Would love to see that feature land, let me know how I can help :)

**Comment by daudtivan** [comment]
To contribute to the point: I'm using Deck to run brainstorming and innovative workshops with my clients, where ideas and contributions come and go in any direction.

Participants create new cards on the fly as discussions progress during the brainstorming session with anything that comes to their mind. There is absolutely no structure for this exercise. The purpose is to collect ideas, which result in many, many cards.

Once the brainstorming is over several ideas look alike or are simple duplicates, so we need to group similar or complementary ideas. One becomes the "master" and all others will become its "child" in a group or hierarchy.

I can't anticipate the hierarchy or grouping, so inner tasks as proposed above can't help in such situations. Tagging to group cards is a more complicated alternative, but can take me there. Naming it a project is incorrect, as it must be voted/approved before it becomes one.

I hope you guys go on with grouping/linking deck cards. Would facilitate my life quite a lot.

**Comment by x29a** [comment]
Does this discussion go in the same direction as [this forum post](https://help.nextcloud.com/t/use-task-and-deck-app-as-different-interfaces-to-task-data/110575)? Because i wondered the same, why not use the same data structure as the Tasks app, just be a different (kanban style) view for it.

The columns would then rather be tags, i guess, or seperate lists?! So that the subtask is free for actual tasks of a card (which would be subcards if i understood the discussion correctly)? With all of their properties and functionality.

**Comment by SjoerdV** [comment]
you can even 

1) have sub-sub-tasks by using the markdown syntax as follows -> **use 4 spaces before the 'sub-sub-task'**

```markdown
* [x] sub-task 1
    * [x] sub-sub-task 1
* [x] sub-task 2
```

rendered like:
* [x] sub-task 1
    * [x] sub-sub-task 1
* [x] sub-task 2

2) add a new line for sub-task preserving indent, but do not create a new sub-task -> **use 2 spaces after the last character in the sub-task**

```markdown
* [x] sub-task 1  
extra comment on new line
* [x] sub-task2
```

rendered like:
* [x] sub-task 1  
extra comment on new line
* [x] sub-task2

**Comment by borisrunakov** [comment]
Using MD for sub-task works, however if subcards are implemented, one could set due date, comments and relationships for each subcard respectively

**Comment by SjoerdV** [comment]
> Using MD for sub-task works, however if subcards were implemented, one could set due date, comments and relationships for each subcard respectively

@borisrunakov I am wondering what the functional difference would be between cards and subcards? Maybe you want a way to organize cards and put them on a timeline or something like that?

I think that would transform Kanban style back to PRINCE2 😉

**Comment by rolandixor** [comment]
@SjoerdV I'm confused as to what hasn't been made clear about this in other comments?

Examples were given here https://github.com/nextcloud/deck/issues/2103#issuecomment-676694458, here https://github.com/nextcloud/deck/issues/2103#issuecomment-653795992, here https://github.com/nextcloud/deck/issues/2103#issuecomment-653844037, here https://github.com/nextcloud/deck/issues/2103#issuecomment-1102767227, and more.

The use case and functional differences have been repeatedly explained by multiple commenters in multiple ways. I'm not trying to be sarcastic here. I'm just genuinely not understanding what is being missed here?

**Comment by Kiendeleo** [comment]
A practical example of this would be something like:

Primary Card: Delpoy New Server (Assigned to a team with an estimated completion date)
Subtasks:
Purchase New Server (Assigned to purchasing with a due date)
Receive New Server and add to inventory (Assigned to Receiving with a due date)
Provision server (Assigned to IT with a due date)
Deploy in Rack (Assigned to IT with a due date)
Migrate Database (Assigned to Database Admin with a due date)
etc...

**Comment by beccon4** [comment]
Is this issue still open? It would be nice to have a similar functionality as in Trello Boards - to group cards hierarchically.

**Comment by jospoortvliet** [comment]
We have now added dependencies. different name - but can be used however you like. If you need tasks done in order, use dependencies. If the order doesn't matter, just use a checklist in the card ;-)

It is not so much hierarchical, but with the GANTT chart, it makes planning quite a bit easier. I'll close this issue - if you want to extend the way it works, do it different, all cool - but pls create a new issue!

**Comment by Grunthos** [comment]
This does not solve the issue of adding fully featured sub tasks with all card features to a card.  

There is a lot of discussion here as to why check lists do not solve the problem.

Please reopen.

**Comment by rolandixor** [comment]
I agree. This isn't a solution for the current issue. It's a separate feature, which, while useful, doesn't solve the problem.

**Comment by garymoon** [comment]
I came looking for this because I figured I was too obtuse to find the right button 😅

Would appreciate a reopen please @jospoortvliet. The change you've pushed, while valuable to some people in this thread I'm sure, does not resolve the issue.
