### ISSUE TITLE
Live-Update on Stacks and Cards

### ISSUE THREAD

**Issue by algorithmennnn** [nextcloud/deck#7166]
When multiple users work together in Nextcloud Deck, changes to stacks and cards (such as moving, editing, or creating) are not updated in real-time for other users. This requires manual page refreshes to see the latest state, which can interrupt the workflow.

Proposed feature:
Implement live updates (e.g., using WebSockets or a similar mechanism) so that all changes to stacks and cards are instantly visible to all participants without needing to reload the page. This would greatly improve the collaborative experience, similar to how other real-time collaboration tools work.

Benefits:

Smoother collaboration for teams.

Reduced chance of conflicts or overwriting changes.

More modern and responsive user experience.

Example use case:
Two users are organizing a project board simultaneously. One user moves a card to a different stack, and the change is instantly reflected on the other user’s screen without requiring a page reload.

**Comment by maxblome** [comment]
This feature already exists. To use it, notify_push must be set up.

https://github.com/nextcloud/notify_push

**Comment by Thatoo** [comment]
It works when moving cards between columns but it doesn't work when editing a card.
Two users opening the same card and updating the description part of it, are not seing what the other is doing.

**Comment by LostinSpacetime** [comment]
Issue is mostly fixed with NC 33.0.2, Deck 1.17.0 and notify_push 1.3.1. Everything I tested is getting updated on different clients/users, except for the comments. Actually, the number of comments is not even updated on the same clients when adding a new comment. This might be the issue in the first place.

**Comment by DesertCookie** [comment]
> Issue is mostly fixed with NC 33.0.2, Deck 1.17.0 and notify_push 1.3.1. Everything I tested is getting updated on different clients/users, except for the comments. Actually, the number of comments is not even updated on the same clients when adding a new comment. This might be the issue in the first place.

Did you also test whether it fixed that when mutliple users are working within Deck, one user saving a card can throw another user out of theirs?

Scenario: User An and B both are within the same Deck, but editing different cards. Uer A closes their card after having made changes to the description. User B receives a notification that another useer changed their card's description (despite that not being true) and user B's card resets to the description it had before user B started editing it.

**Comment by LostinSpacetime** [comment]
> Did you also test whether it fixed that when mutliple users are working within Deck, one user saving a card can throw another user out of theirs?
> 
> Scenario: User An and B both are within the same Deck, but editing different cards. Uer A closes their card after having made changes to the description. User B receives a notification that another useer changed their card's description (despite that not being true) and user B's card resets to the description it had before user B started editing it.

I tested with two users working at the same deck and different cards. The changes are synced within 2-3 seconds and shown to the other user without a message/warning. Only if both users are making changes to the same card I get a message/warning. The changes are also synced within 2-3 seconds.

Deck 1.17.3
NC 33.0.5

**Comment by DesertCookie** [comment]
> I tested with two users working at the same deck and different cards. The changes are synced within 2-3 seconds and shown to the other user without a message/warning. Only if both users are making changes to the same card I get a message/warning. The changes are also synced within 2-3 seconds.
> 
> Deck 1.17.3 NC 33.0.5

Interesting. I still sometimes have issues where I am thrown out of my card, just by having someone else be in the same Deck. That's rarely, luckily enough, and only happens once a day, or so.

The real issue remains someone being in the same card - just having that open in some background tab from hours earlier - and it throwing me out frequently, despite that person not doing anything.
