### ISSUE TITLE
Emails Missing Card Name

### ISSUE THREAD

**Issue by mikshepard** [nextcloud/deck#769]
**Describe the bug**
When enabling the email notifications for Deck, the activity sent in the email doesn't show the card name, instead it's just {card}.  For example:

```
Today at 12:52 PM
John Doe has updated the due date of {card} to 2018-12-24T18:52:10+00:00

Today at 1:00 PM
has updated the description {card} in In Progress on John's Tasks
```

**To Reproduce**
1. User A enables both email Activity options in the user settings
2. User B creates a new card and assigns it to User A
3. User A gets an email but the card name is replaced with {card}

**Expected behavior**
The email should contain the card name.

**Operating system**:
Debian Jessie 8.11
**Web server:**
Apache 2.4.10
**Database:**
mysql 5.7.24
**PHP version:**
php v7.1.24
**Nextcloud version:** (see Nextcloud admin page)
14.0.3
**Where did you install Nextcloud from:**
source tarball

**Comment by juliushaertl** [comment]
Which version of deck did you use?

**Comment by mikshepard** [comment]
My apologies for forgetting that, I'm on v0.5.1

**Comment by juliushaertl** [comment]
I cannot reproduce with 0.5.1 anymore, this was a bug on 0.5.0 (#721) which should have been fixed with #761. Could it be possible that those activity entries were generated before upgrading to 0.5.1?

**Comment by mikshepard** [comment]
No, I created new cards for testing this after the update to 0.5.1, and that was the results.  Today I updated Nextcloud to v.14.0.4.2, created a new board, new card, assigned a user, and still have the same results in the email.  Apache was restarted to clear any php cache as well.

What info can I provide to help debug this?

**Comment by juliushaertl** [comment]
@mikshepard Can you please try this again? I just tried to reproduce this with the freshly release 0.5.2 and it works fine for me:

![image](https://user-images.githubusercontent.com/3404133/50290911-5e352b80-046d-11e9-9add-37ee0ea9b32c.png)

**Comment by mikshepard** [comment]
@juliushaertl I'm on 0.5.2 and am still having the issue, see below (I blocked out names with red):

![image](https://user-images.githubusercontent.com/3514599/50657908-61e0ac00-0f5d-11e9-9aaf-12696ac1db38.png)

![image](https://user-images.githubusercontent.com/3514599/50658012-aa986500-0f5d-11e9-8ba7-9fefa275fd2b.png)

**Comment by juliushaertl** [comment]
Ok, maybe it is an issue that just happens on Nextcloud 14, I'll have a look.

**Comment by mikshepard** [comment]
Thank you.  Let me know if I can provide any further info to help

**Comment by bpcurse** [comment]
I can confirm that this is still an issue on our 14.0.4 instance (shared hosting) but not on 15.0.0 (own server) 
Both using Deck 0.5.2

**Comment by mamatt** [comment]
I can confirm that the bug is present on NC14.0.3 /Deck 0.5.1 but only on activity mail.
There is no issue with the activity feed

**Comment by juliushaertl** [comment]
14 is no longer supported by deck, so I'm closing this for now as I have not been able to reproduce. Feel free to reopen if it still occurs with Nextcloud 15/16 on deck 0.6.1
